package com.ares3.telemetry.dto;

import java.time.Instant;

/**
 * A Watney-style survival log entry generated by the Claude advisor, paired with
 * a deterministic {@link RiskLevel} classification of the current telemetry.
 */
public record WatneyAdviceDto(
        int sol,
        String advice,
        RiskLevel riskLevel,
        Instant timestamp
) {
}
